# Header

menu:
  ä¸»é¡µ: https://ayang818.gitee.io/blog/

# SubNav
subnav:
  github: "https://github.com/ayang818"
  zhihu: "https://www.zhihu.com/people/yang-yang-64-89-86/activities"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  bilibili: "https://space.bilibili.com/35953658"
  #acfun: "#"
  mail: "mailto:ayang818@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# æ˜¯å¦éœ€è¦ä¿®æ”¹ root è·¯å¾„
# å¦‚æœæ‚¨çš„ç½‘ç«™å­˜æ”¾åœ¨å­ç›®å½•ä¸­ï¼Œä¾‹å¦‚ http://yoursite.com/blogï¼Œ
# è¯·å°†æ‚¨çš„ url è®¾ä¸º http://yoursite.com/blog å¹¶æŠŠ root è®¾ä¸º /blog/ã€‚
root: /blog

# Content

# æ–‡ç« å¤ªé•¿ï¼Œæˆªæ–­æŒ‰é’®æ–‡å­—
excerpt_link: "more"
# æ–‡ç« å¡ç‰‡å³ä¸‹è§’å¸¸é©»é“¾æ¥ï¼Œä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
show_all_link: 'å±•å¼€å…¨æ–‡'
# æ•°å­¦å…¬å¼
mathjax: true
# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: true

# æ‰“èµ
# æ‰“èµtypeè®¾å®šï¼š0-å…³é—­æ‰“èµï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰reward:trueå±æ€§ï¼Œæ‰æœ‰æ‰“èµï¼› 2-æ‰€æœ‰æ–‡ç« å‡æœ‰æ‰“èµ
reward_type: 2
# æ‰“èµwording
reward_wording: 'è°¢è°¢ä½ çš„èµèµï¼'
# æ”¯ä»˜å®äºŒç»´ç å›¾ç‰‡åœ°å€ï¼Œè·Ÿä½ è®¾ç½®å¤´åƒçš„æ–¹å¼ä¸€æ ·ã€‚æ¯”å¦‚ï¼š/assets/img/alipay.jpg
alipay: https://computernetworking.oss-cn-hongkong.aliyuncs.com/temppic/alipay.jpg
# å¾®ä¿¡äºŒç»´ç å›¾ç‰‡åœ°å€
weixin: 

# ç›®å½•
# ç›®å½•è®¾å®šï¼š0-ä¸æ˜¾ç¤ºç›®å½•ï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰toc:trueå±æ€§ï¼Œæ‰æœ‰ç›®å½•ï¼› 2-æ‰€æœ‰æ–‡ç« å‡æ˜¾ç¤ºç›®å½•
toc: 2
# æ ¹æ®è‡ªå·±çš„ä¹ æƒ¯æ¥è®¾ç½®ï¼Œå¦‚æœä½ çš„ç›®å½•æ ‡é¢˜ä¹ æƒ¯æœ‰æ ‡å·ï¼Œç½®ä¸ºtrueå³å¯éšè—hexoé‡å¤çš„åºå·ï¼›å¦åˆ™ç½®ä¸ºfalse
toc_hide_index: true
# ç›®å½•ä¸ºç©ºæ—¶çš„æç¤º
toc_empty_wording: 'ç›®å½•ï¼Œä¸å­˜åœ¨çš„â€¦'

# æ˜¯å¦æœ‰å¿«é€Ÿå›åˆ°é¡¶éƒ¨çš„æŒ‰é’®
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: https://upload-serve.oss-cn-beijing.aliyuncs.com/image/aliosstest.jpg

#ä½ çš„å¤´åƒurl
avatar: https://upload-serve.oss-cn-beijing.aliyuncs.com/avatar/avatar.jpg

#æ˜¯å¦å¼€å¯åˆ†äº«
share_jia: true

#è¯„è®ºï¼š1ã€å¤šè¯´ï¼›2ã€ç½‘æ˜“äº‘è·Ÿå¸–ï¼›3ã€ç•…è¨€ï¼›4ã€Disqusï¼›5ã€Gitment
#ä¸éœ€è¦ä½¿ç”¨æŸé¡¹ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰
#å…·ä½“è¯·å‚è€ƒwikiï¼šhttps://github.com/litten/hexo-theme-yilia/wiki/

#1ã€å¤šè¯´
duoshuo: false

#2ã€ç½‘æ˜“äº‘è·Ÿå¸–
wangyiyun: false

#3ã€ç•…è¨€
changyan_appid: false
changyan_conf: false

#4ã€Disqus åœ¨hexoæ ¹ç›®å½•çš„configé‡Œä¹Ÿæœ‰disqus_shortnameå­—æ®µï¼Œä¼˜å…ˆä½¿ç”¨yiliaçš„
disqus: false

#5ã€Gitment
gitment_owner: false      #ä½ çš„ GitHub ID
gitment_repo: ''          #å­˜å‚¨è¯„è®ºçš„ repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

gitalk:
  enable:  true
  githubID:  ayang818   
  repo:  'comment-repo'
  ClientID:  '2df080a3f11a34fc4f0d'
  ClientSecret:  '3c6fefb8587a575f94ca5a00cdf6ad9e41ad0c0c'
  adminUser:  ayang818
  distractionFreeMode: true

# æ ·å¼å®šåˆ¶ - ä¸€èˆ¬ä¸éœ€è¦ä¿®æ”¹ï¼Œé™¤éæœ‰å¾ˆå¼ºçš„å®šåˆ¶æ¬²æœ›â€¦
style:
  # å¤´åƒä¸Šé¢çš„èƒŒæ™¯é¢œè‰²
  header: '#4d4d4d'
  # å³æ»‘æ¿å—èƒŒæ™¯
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# sliderçš„è®¾ç½®
slider:
  # æ˜¯å¦é»˜è®¤å±•å¼€tagsæ¿å—
  showTags: false

# æ™ºèƒ½èœå•
# å¦‚ä¸éœ€è¦ï¼Œå°†è¯¥å¯¹åº”é¡¹ç½®ä¸ºfalse
# æ¯”å¦‚
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: 'æ‰€æœ‰æ–‡ç« '
  friends: 'å‹é“¾'
  aboutme: 'å…³äºæˆ‘'

friends:
  æœªæ¥çš„å¥¹(null): '#'
  è½¬è½¬: https://wzyxv1n.top
  syhå¤§ä½¬: https://blog.csdn.net/syh0313
  ä¼¦å“¥: https://ar8327k.top
  
aboutme: '
  åŸºæœ¬ä¿¡æ¯</br>
  1. æ­å·ç”µå­ç§‘æŠ€å¤§å­¦</br>
  2. ä¿¡æ¯ç®¡ç†ä¸ä¿¡æ¯ç³»ç»Ÿ</br>
  3. å¤§äºŒåœ¨è¯»</br>
  4. Githubé«˜å¼ºåº¦ä½¿ç”¨ç”¨æˆ·</br>
  5. çƒ­çˆ±è‡ªå·±é€ è½®å­, çƒ­çˆ±å¼€æº</br>
  6. å•¥ç©æ„éƒ½æ„¿æ„å»æ£é¼“ä¸€ä¸‹</br>
  7. å–œæ¬¢Alibaba å’Œ Google</br>
</br>
  èŒä¸šç»å†</br>
  2019.6 - 2019.10 : è çš‡å¨±ä¹ç§‘æŠ€äº‹åŠ¡æ‰€(ğŸèµ›ä¸œ)Â·å·¥å…·äºº</br>
  2019.11 - ~ : è€è€å®å®å‘†åœ¨å­¦æ ¡(å¸Œæœ›å¤§ä¸‰çš„æ—¶å€™èƒ½æºœå‡ºå­¦æ ¡å»é˜¿é‡Œå®ä¹ )</br>
'